name: Build and Unit Test

on:
  push
  # pull_request:
  #   branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set default Xamarin SDK versions
      run: |
        $VM_ASSETS/select-xamarin-sdk-v2.sh --mono=6.12.0 --android=12.0
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: nuget restore CaffeineCrashCue.sln
    # - name: Build Base
    #   run: dotnet build -c ExcludePlatforms --no-restore
    # - name: Build Android
    #   run: msbuild ./CaffeineCrashCue/CaffeineCrashCue.Android/CaffeineCrashCue.Android.csproj /t:PackageForAndroid /p:Configuration=Debug
    # - name: Test
    #   run: dotnet test -c ExcludePlatforms --no-build --verbosity normal
    - name: Create and Sign APK
      run: msbuild ./CaffeineCrashCue/CaffeineCrashCue.Android/CaffeineCrashCue.Android.csproj /t:SignAndroidPackage /p:Configuration=Release
    - name: Upload apk
      uses: actions/upload-artifact@v2
      with:
        name: CaffeineCrashCue.apk
        path: /*.apk
