name: .NET Build/Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set default Xamarin SDK versions
      run: |
        $VM_ASSETS/select-xamarin-sdk-v2.sh --mono=6.12.0 --android=11.0
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: nuget restore CaffeineCrashCue.sln
    - name: Build
      run: msbuild CaffeineCrashCue.sln
    - name: Test
      run: dotnet test --no-build --verbosity normal
